name: 'Update pr description async'
description: 'Update pr description asynchronous with a timeout, to avoid two updates at the same time'
inputs:
  prDescAppend:
    description: 'append this to pr'
    required: true
  token:
    description: 'the git token'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
