name: 'Update pr description async'
description: 'Update pr description asynchronous with a timeout, to avoid two updates at the same time'
inputs:
  maxTimeout:
    description: 'maximum timeout in seconds for updating the description'
    required: false
    default: 25
  prDescAppend:
    description: 'append this to pr'
    required: true
  isTicketUpdate:
    description: 'updated ticket link = true, preview links = false'
    required: false
    default: false
  token:
    description: 'the git token'
    required: true
runs:
  using: 'node16'
  main: 'dist/index.js'
